name: openqa
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  openqa:
    runs-on: ubuntu-latest
    name: "Trigger an openQA test with custom new test"
    container:
      image: curlimages/curl
    steps:
    - name: Trigger openQA test
      run: |
        curl -u ${{ secrets.OPENQA_O3_USER_KEY_SECRET }} \
          -d "arch=x86_64&flavor=test&version=Tumbleweed&machine=64bit&test=feature_next&casedir=https://github.com/${{ github.repository }}#${GITHUB_REF#refs/heads/}&distri=openqa&hdd_1=opensuse-Tumbleweed-x86_64@64bit-2G-:TW.7907.qcow2&schedule=tests/install/boot.py" \
          https://openqa.opensuse.org/api/v1/jobs
